apiVersion: v1
kind: Service
metadata:
  name: planiot-dropper-prioritizer-service
spec:
  type: NodePort
  ports:
    - port: 8880
      protocol: TCP
      targetPort: 8880
      name: http
  selector:
    app: planiot-dropper-prioritizer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: planiot-dropper-prioritizer-deployment
spec:
  selector:
    matchLabels:
      app: planiot-dropper-prioritizer
  replicas: 1
  template:
    metadata:
      labels:
        app: planiot-dropper-prioritizer
    spec:
      containers:
        - name: planiot-dropper-prioritizer-container
          image: index.docker.io/nirminedocker/planiot-dropper_prioritizer:v0.0.2
          imagePullPolicy: Always