apiVersion: v1
kind: Service
metadata:
  name: planiot-subscribers-service
spec:
  type: NodePort
  ports:
    - port: 8787
      protocol: TCP
      targetPort: 8787
      name: http
  selector:
    app: planiot-subscribers
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planiot-subscribers-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planiot-subscribers-service
                port:
                  number: 8787
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planiot-subscribers-deployment
  annotations:
    kubernetes.io/ingress-bandwidth: 10M
    # Egress bandwidth
    kubernetes.io/egress-bandwidth: 10M
spec:
  selector:
    matchLabels:
      app: planiot-subscribers
  replicas: 1
  template:
    metadata:
      labels:
        app: planiot-publishers
    spec:
      containers:
        - name: planiot-subscribers-kubernetes
          image: docker-planiot-publishers:latest
          ports:
            - containerPort: 8787
          imagePullPolicy : IfNotPresent
