apiVersion: v1
kind: Service
metadata:
  name: planiot-api-service
spec:
  type: NodePort
  ports:
    - port: 8780
      protocol: TCP
      targetPort: 8780
      nodePort : 31163
      name: http
  selector:
    app: planiot-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/limit-rate: "1000m"
spec:
  rules:
    - http:
        paths:
          - path: /planiotAPI
            pathType: Prefix
            backend:
              service:
                name: planiot-api-service
                port:
                  number: 8780
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planiot-api-deployment
  annotations:
    kubernetes.io/ingress-bandwidth: 1M
  # Egress bandwidth
    kubernetes.io/egress-bandwidth: 1M
spec:
  selector:
    matchLabels:
      app: planiot-api
  replicas: 2
  template:
    metadata:
      labels:
        app: planiot-api
    spec:
      containers:
        - name: planiot-api-kubernetes
          image: nirminedocker/planiot-api:v0.0.1
          ports:
            - containerPort: 8780
          imagePullPolicy : IfNotPresent
